name: crypto04
services:
  server:
    build: .
    ports:
      - "5004:1338"
    environment:
      - FLAG=pascalCTF{sm00th_0rd3rs_m4k3_3cc_n0t_s0_h4rd_4ft3r_4ll}
    restart: unless-stopped
    container_name: crypto04-curve
