name: web04
services:
  pdfile:
    build:
      context: .
      args:
        - FLAG=pascalCTF{xml_t0_pdf_1s_th3_n3xt_b1g_th1ng}
    ports:
      - "127.0.0.1:8004:5000"
    volumes:
      - uploads:/app/uploads
    environment:
      - FLASK_ENV=production
    container_name: web04-pdfile
    restart: unless-stopped

volumes:
  uploads: