name: ai04
services:
  app:
    build: .
    container_name: ai04-app
    restart: unless-stopped
    env_file: .env
    ports:
      - "127.0.0.1:${PORT}:${PORT}"
    depends_on:
      - database
  
  database:
    image: mongo
    container_name: ai04-database
    restart: always
    env_file: .env
    volumes:
      - mongo-data-ai04:/data/db
      - mongodb-log-ai04:/var/log/mongodb
    command: mongod --quiet --logpath /var/log/mongodb/mongo.log --logappend --bind_ip_all

volumes:
  mongo-data-ai04:
  mongodb-log-ai04: